export const HMS_URLS = {
  ROOT: '/health-management',
  ADMIN: '/health-management/admin',
  ADMIN_DASHBOARD: '/health-management/admin/dashboard',
  ADMIN_SETTINGS: '/health-management/admin/settings',
  DOCTOR: '/health-management/doctor',
  DOCTOR_DASHBOARD: '/health-management/doctor/dashboard',
  PHARMACIST: '/health-management/pharmacist',
  EMPLOYEE: '/health-management/employee',
  EMPLOYEE_DASHBOARD: '/health-management/employee/dashboard',
  MEMBERSHIPS: '/health-management/memberships',
  ADD_MEMBERSHIP: '/health-management/memberships/add',
  RECORDS: '/health-management/records',
  ADD_RECORD: '/health-management/records/add',
  DOCTORS: '/health-management/doctors',
  STOCK: '/health-management/stock',
  ADD_STOCK: '/health-management/stock/add',
  PRESCRIPTIONS: '/health-management/prescriptions',
  ADD_PRESCRIPTION: '/health-management/prescriptions/add',
  DISPENSARY: '/health-management/dispensary',
  ADD_DISPENSARY: '/health-management/dispensary/add',
  APPOINTMENTS: '/health-management/appointments',
  GUEST_USERS: '/health-management/guest-users',
  ADD_GUEST_USER: '/health-management/guest-users/add',
  REPORTS: '/health-management/reports',
  SUBSCRIPTIONS: '/health-management/subscriptions',
};
